modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "moderninline"
version = "${version}"
displayName = "ModernInline"
authors = "yahvk"
description = '''

'''
#logoFile = ""

[[dependencies.moderninline]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderninline]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

