modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "moderninline"
version = "${version}"
displayName = "ModernInline"
authors = "yahvk"
description = '''
A compatible mod for Modern UI and Inline.
'''
logoFile = "assets/moderninline/icon.png"

[[dependencies.moderninline]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderninline]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderninline]]
modId = "modernui"
mandatory = true
versionRange = "[3.11.1.0,3.11.2.0)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moderninline]]
modId = "inline"
mandatory = true
versionRange = "[1.20.1-1.0.1,)"
ordering = "NONE"
side = "CLIENT"
