modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "moderninline"
version = "${version}"
displayName = "ModernInline"
authors = "yahvk"
description = '''
A compatible mod for Modern UI and Inline.
'''
logoFile = "assets/moderninline/icon.png"

[[dependencies.moderninline]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderninline]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderninline]]
modId = "modernui"
mandatory = true
versionRange = "[3.11.1.0,4.0.0.0)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moderninline]]
modId = "inline"
mandatory = true
versionRange = "[1.20.1-1.0.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "moderninline.mixins.json"